### PR TITLE
Add support for 13.4

### PR DESCRIPTION
**Pull request by Endunry**
Add revision number for 13.4 and added the pointers

### CODE REVIEW

**Comment by Endunry** [comment]
ok nvm, i cant find a good revision version pointer for 13.4. It works sometimes.
What was your strategy to finding the rev numbers to get the version correctly?

**Comment by bebcky** [comment]
I used the openttd debug symbols and a debugger like Visual Studio to find all variable locations. I can find the version number offset myself if you'd like

**Comment by bebcky** [comment]
I found an offset of `0x0094cd24` for `_openttd_revision` in https://github.com/OpenTTD/OpenTTD/blob/13.4/src/rev.h using a debugger (was annoying to get, my debugger kept crashing on me haha)

**Comment by bebcky** [comment]
I tried the offset on my machine and it worked! I updated the offset and cleaned up the formatting in a commit, and it's all good to merge. Thank you very much for the contribution!

**Pull request merged**
